<html lang="en">

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/light.min.css">
</head>
<body>

    <form method="post" action="/postTask">
      <label>Todo Item:</label><br>
      <input type="text" id="task" name="task" placeholder="Learn Programming!"><br>
      <input type="submit" value="Submit">
    </form>

    <a href="/">Back</a> <br>

</body>
</html>